name: Build, push image to Docker Hub and deploy to KIND

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} # Use a GitHub secret for security

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: . # The directory containing your Dockerfile
          file: ./Dockerfile
          push: true # Set to true to push the image to the registry
          tags: ${{ secrets.DOCKER_USERNAME }}/node-project:latest # Tag format: namespace/repository:tag
          cache-from: type=gha # Use GitHub Actions cache for faster builds
          cache-to: type=gha,mode=max

  deploy:
    runs-on: [self-hosted, windows, x64]
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure KIND cluster exists
        run: |
          kind get clusters | findstr dev-cluster || kind create cluster --name dev-cluster --image kindest/node:v1.29.2

      - name: Use KIND context
        run: kubectl config use-context kind-dev-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/node-app
